-- delete from article_comment;
-- delete from article;

insert into article (content, created_at, created_by, hashtag, modified_at, modified_by, title) values ('clear-thinking', '2023-08-02', 'Yakijo', 'Carling', '2023-04-28', 'Yodel', 'Bryant Army Heliport');
insert into article (content, created_at, created_by, hashtag, modified_at, modified_by, title) values ('solution-oriented', '2023-01-27', 'Yadel', 'Eugenie', '2022-11-10', 'Jabbersphere', 'Mopah Airport');
insert into article (content, created_at, created_by, hashtag, modified_at, modified_by, title) values ('Advanced', '2022-09-29', 'Abata', 'Gwyneth', '2023-01-07', 'Devpoint', 'Half Moon Bay Airport');
insert into article (content, created_at, created_by, hashtag, modified_at, modified_by, title) values ('Multi-layered', '2023-09-04', 'Youopia', 'Holly', '2023-03-31', 'Vinte', 'Lagunillas Airport');
insert into article (content, created_at, created_by, hashtag, modified_at, modified_by, title) values ('contextually-based', '2023-02-04', 'Yamia', 'Roley', '2023-09-06', 'Yozio', 'Yapsiei Airport');
insert into article (content, created_at, created_by, hashtag, modified_at, modified_by, title) values ('challenge', '2023-04-18', 'Yacero', 'Charisse', '2022-10-10', 'Skipstorm', 'Zweibrücken Airport');
insert into article (content, created_at, created_by, hashtag, modified_at, modified_by, title) values ('Universal', '2022-10-21', 'Yamia', 'Tann', '2022-10-12', 'Riffpedia', 'East Midlands Airport');
insert into article (content, created_at, created_by, hashtag, modified_at, modified_by, title) values ('circuit', '2023-04-09', 'Plajo', 'Llewellyn', '2022-11-27', 'Meevee', 'Ziguinchor Airport');
insert into article (content, created_at, created_by, hashtag, modified_at, modified_by, title) values ('Sharable', '2023-07-11', 'Linkbuzz', 'Hurlee', '2023-01-05', 'Myworks', 'Tuguegarao Airport');
insert into article (content, created_at, created_by, hashtag, modified_at, modified_by, title) values ('Face to face', '2022-11-28', 'Ntag', 'Berne', '2023-02-01', 'Thoughtstorm', 'Maripasoula Airport');
insert into article (content, created_at, created_by, hashtag, modified_at, modified_by, title) values ('user-facing', '2022-10-06', 'Fiveclub', 'Erin', '2023-02-08', 'Thoughtmix', 'Dublin Airport');
insert into article (content, created_at, created_by, hashtag, modified_at, modified_by, title) values ('Seamless', '2023-08-27', 'Quire', 'Sallyann', '2022-10-29', 'Roodel', 'Hornafjörður Airport');
insert into article (content, created_at, created_by, hashtag, modified_at, modified_by, title) values ('forecast', '2023-04-25', 'Topiczoom', 'Andriana', '2023-02-22', 'Podcat', 'Greenville Sinoe Airport');
insert into article (content, created_at, created_by, hashtag, modified_at, modified_by, title) values ('Graphical User Interface', '2023-05-07', 'Podcat', 'Brinn', '2023-03-25', 'Browseblab', 'Vologda Airport');
insert into article (content, created_at, created_by, hashtag, modified_at, modified_by, title) values ('groupware', '2023-02-11', 'Dabfeed', 'Normand', '2022-12-23', 'Voomm', 'Tarapaina Airport');
insert into article (content, created_at, created_by, hashtag, modified_at, modified_by, title) values ('Ameliorated', '2023-06-24', 'Snaptags', 'Iggie', '2022-12-25', 'Ozu', 'Los Perales Airport');
insert into article (content, created_at, created_by, hashtag, modified_at, modified_by, title) values ('Persevering', '2023-02-10', 'Meedoo', 'Binky', '2023-07-01', 'Yadel', 'Dawei Airport');
insert into article (content, created_at, created_by, hashtag, modified_at, modified_by, title) values ('customer loyalty', '2023-02-12', 'Tekfly', 'Hayyim', '2022-11-29', 'Devshare', 'Tapini Airport');
insert into article (content, created_at, created_by, hashtag, modified_at, modified_by, title) values ('cohesive', '2022-12-14', 'Mynte', 'Dodie', '2023-06-07', 'Skyvu', 'Gladwin Zettel Memorial Airport');
insert into article (content, created_at, created_by, hashtag, modified_at, modified_by, title) values ('firmware', '2023-08-02', 'Jabbercube', 'Weber', '2022-10-07', 'Realblab', 'North Texas Regional Airport/Perrin Field');

insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Programmable', '2023-01-07', 'Leexo', 1, '2023-06-19', 'Rhynoodle');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('User-centric', '2023-04-16', 'Trilith', 1, '2022-11-27', 'Skaboo');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('regional', '2023-07-06', 'Lajo', 20, '2023-07-03', 'Kaymbo');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Expanded', '2023-07-04', 'Meejo', 5, '2023-04-05', 'Eayo');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('challenge', '2023-05-25', 'Pixonyx', 18, '2023-07-28', 'Eadel');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('toolset', '2023-04-06', 'Jaxbean', 8, '2022-11-23', 'Browseblab');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Fundamental', '2023-01-25', 'Jabbersphere', 10, '2022-10-18', 'Centimia');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('web-enabled', '2023-08-21', 'Voonte', 13, '2023-06-06', 'Gigazoom');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Networked', '2022-10-01', 'Livetube', 18, '2022-11-23', 'Cogidoo');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('mobile', '2022-10-21', 'Lazzy', 18, '2022-09-13', 'Photobug');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Progressive', '2022-12-16', 'Gigazoom', 6, '2022-10-16', 'Kwinu');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Triple-buffered', '2022-11-23', 'Twitternation', 3, '2023-02-24', 'Voomm');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('24 hour', '2022-09-15', 'Kwideo', 19, '2023-01-19', 'Realbridge');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('systematic', '2023-01-15', 'Babbleset', 15, '2023-06-18', 'Thoughtbridge');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Ameliorated', '2023-04-06', 'Flipstorm', 10, '2023-06-15', 'Tagchat');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('web-enabled', '2023-02-07', 'Zooveo', 3, '2023-03-07', 'Yakitri');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('3rd generation', '2022-12-06', 'Kazu', 17, '2023-01-04', 'Fivespan');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('orchestration', '2022-11-10', 'Camimbo', 3, '2023-07-20', 'Avamm');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Graphical User Interface', '2023-06-14', 'Ainyx', 16, '2023-09-02', 'Oloo');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('project', '2022-12-19', 'Devify', 11, '2023-09-03', 'Eare');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('systemic', '2023-08-19', 'Jaxworks', 12, '2023-06-01', 'Flashset');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('explicit', '2023-03-10', 'Voolia', 18, '2022-10-28', 'Eadel');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Fully-configurable', '2023-01-18', 'Zoomzone', 11, '2023-03-22', 'Zoovu');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Innovative', '2023-04-12', 'Zoomdog', 2, '2023-07-01', 'Jabberstorm');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('project', '2022-12-27', 'Jazzy', 8, '2023-07-23', 'Aivee');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Extended', '2023-02-23', 'Bluezoom', 19, '2022-12-06', 'Gabspot');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('software', '2023-05-28', 'Quatz', 20, '2022-11-18', 'Trupe');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('standardization', '2023-07-28', 'Teklist', 7, '2023-02-09', 'Reallinks');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Monitored', '2023-03-23', 'Rhyzio', 4, '2022-09-17', 'Kimia');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Optional', '2023-07-16', 'Thoughtbeat', 2, '2023-07-14', 'Gabvine');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('challenge', '2022-11-30', 'Buzzbean', 8, '2023-02-05', 'Gigazoom');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('data-warehouse', '2022-09-21', 'Jaxspan', 3, '2023-07-01', 'Skajo');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Re-contextualized', '2023-08-16', 'Eabox', 11, '2023-01-08', 'Ntags');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Cross-group', '2023-02-12', 'Mybuzz', 16, '2022-09-21', 'Pixoboo');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('time-frame', '2023-03-14', 'Chatterbridge', 9, '2022-11-21', 'Devshare');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Programmable', '2023-08-23', 'Lajo', 15, '2023-01-13', 'Bubblebox');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('internet solution', '2022-11-10', 'Jatri', 11, '2023-09-03', 'Shuffledrive');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('installation', '2023-02-11', 'Twinder', 8, '2022-11-04', 'Jaxspan');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('object-oriented', '2022-11-28', 'Topdrive', 5, '2022-10-25', 'Avamm');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('neural-net', '2023-07-06', 'Dabjam', 17, '2023-06-07', 'Oyoba');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('contextually-based', '2023-02-12', 'Yotz', 4, '2023-04-29', 'Thoughtbridge');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('system engine', '2023-01-26', 'Dabshots', 17, '2023-08-28', 'Kanoodle');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('definition', '2023-07-06', 'Wikido', 12, '2022-12-01', 'Oozz');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Reduced', '2023-05-20', 'Katz', 11, '2023-05-08', 'Chatterpoint');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('24/7', '2023-07-12', 'Dynazzy', 11, '2022-11-26', 'Linktype');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('initiative', '2023-03-25', 'Npath', 7, '2023-02-01', 'Jaxnation');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('empowering', '2023-01-27', 'Zoonder', 8, '2023-08-25', 'Flipopia');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('mobile', '2023-04-14', 'Rhyzio', 11, '2022-09-11', 'Riffpath');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Streamlined', '2022-12-16', 'Dabjam', 11, '2023-01-09', 'Cogibox');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('multi-tasking', '2022-11-11', 'Nlounge', 13, '2023-05-16', 'Eimbee');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('exuding', '2023-06-24', 'Feednation', 3, '2023-04-17', 'Dabfeed');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('intermediate', '2023-08-15', 'Leenti', 3, '2023-06-24', 'Leenti');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('monitoring', '2022-12-14', 'Photobug', 3, '2022-09-21', 'Youtags');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Open-source', '2022-11-29', 'Skaboo', 11, '2023-02-23', 'Gigashots');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('24/7', '2022-09-16', 'Einti', 20, '2023-05-25', 'Photofeed');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Realigned', '2023-08-11', 'Jabbersphere', 14, '2023-03-09', 'Aivee');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Graphical User Interface', '2023-03-04', 'Devbug', 9, '2023-09-08', 'Jaxspan');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('complexity', '2022-09-20', 'Yotz', 13, '2023-07-27', 'Photofeed');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Face to face', '2022-10-18', 'Midel', 3, '2023-04-15', 'Flashset');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Open-source', '2023-08-21', 'Quamba', 10, '2023-05-17', 'Fanoodle');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('reciprocal', '2023-07-10', 'Edgewire', 3, '2022-10-25', 'Yata');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('regional', '2023-08-31', 'Janyx', 12, '2023-04-12', 'Feedbug');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('uniform', '2023-05-25', 'Bubblebox', 5, '2023-06-10', 'Skyba');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Configurable', '2022-10-17', 'Leexo', 12, '2023-06-29', 'Edgeclub');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('paradigm', '2023-03-28', 'Fliptune', 11, '2023-09-03', 'Gigazoom');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('collaboration', '2023-02-24', 'Brainlounge', 7, '2023-08-23', 'Zoomdog');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('web-enabled', '2023-02-22', 'Fivebridge', 9, '2022-12-26', 'Twitterbridge');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('emulation', '2023-01-08', 'Topicshots', 11, '2022-12-30', 'Oyoloo');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Re-engineered', '2023-01-30', 'Photolist', 15, '2023-01-03', 'Mynte');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Triple-buffered', '2023-04-29', 'Topiczoom', 11, '2023-04-16', 'Eayo');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Secured', '2022-10-26', 'Chatterbridge', 13, '2023-08-23', 'Snaptags');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('database', '2023-02-11', 'Roomm', 3, '2022-10-23', 'Jaxworks');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Diverse', '2022-12-03', 'Mydo', 3, '2023-09-02', 'Divanoodle');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('array', '2022-10-18', 'Plambee', 6, '2023-02-24', 'Feedmix');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('tangible', '2023-01-31', 'Kwinu', 6, '2022-09-25', 'Ntags');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Business-focused', '2023-08-15', 'Quinu', 1, '2023-03-17', 'Twitterbridge');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('policy', '2022-11-13', 'Livefish', 20, '2023-05-22', 'Wordtune');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Compatible', '2023-02-09', 'Ntags', 9, '2023-07-13', 'Voonte');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('info-mediaries', '2023-02-10', 'Quimm', 11, '2022-12-22', 'Aibox');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('local area network', '2023-01-20', 'Meembee', 2, '2023-09-05', 'Kwideo');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('bi-directional', '2022-10-18', 'Twimbo', 11, '2022-10-18', 'Myworks');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('scalable', '2023-06-30', 'Ailane', 1, '2023-03-06', 'Browseblab');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('mission-critical', '2022-12-25', 'Vitz', 4, '2023-05-17', 'Voonte');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Team-oriented', '2023-05-25', 'Meejo', 16, '2022-12-03', 'Rhynyx');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('emulation', '2023-04-02', 'Eazzy', 9, '2023-03-11', 'Wikizz');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Public-key', '2022-11-08', 'Brainbox', 20, '2022-11-06', 'Einti');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Grass-roots', '2023-07-05', 'Realbridge', 9, '2023-07-23', 'Buzzshare');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Automated', '2023-07-10', 'Zoomzone', 16, '2023-08-01', 'Edgeblab');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('projection', '2023-06-14', 'Flashset', 7, '2022-10-07', 'Gigazoom');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('responsive', '2023-03-11', 'Browsezoom', 17, '2023-08-08', 'Jetpulse');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Robust', '2022-12-10', 'Kazu', 6, '2023-01-29', 'Eare');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Centralized', '2022-10-11', 'Quinu', 9, '2023-01-14', 'Riffwire');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('responsive', '2023-01-08', 'Zoozzy', 13, '2023-02-10', 'Divavu');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('protocol', '2023-02-12', 'Einti', 8, '2022-11-25', 'Gigazoom');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('explicit', '2022-09-12', 'Abata', 4, '2023-06-08', 'Youbridge');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('eco-centric', '2023-01-12', 'Realmix', 4, '2023-03-04', 'Twitternation');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Persistent', '2023-03-22', 'Tagcat', 4, '2023-05-21', 'Realmix');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Extended', '2023-05-26', 'Quire', 9, '2022-10-18', 'Fivechat');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('well-modulated', '2023-05-18', 'Eabox', 18, '2023-09-03', 'Meedoo');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Customer-focused', '2023-07-17', 'Aivee', 7, '2022-09-17', 'Twimbo');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Expanded', '2022-11-03', 'Zoomzone', 8, '2023-08-10', 'Gevee');
insert into article_Comment (content, created_at, created_by, article_id, modified_at, modified_by) values ('Exclusive', '2022-12-14', 'Miboo', 20, '2023-08-22', 'Cogibox');